name: Output Issue Information to Shell

on: issues

jobs:
  output_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Issues (GitHub context)
        run: echo "${{ toJSON(github)['event'] }}"
